# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'jekyll'
gem 'github-pages', group: :jekyll_plugins
gem 'jemoji', group: :jekyll_plugins

gem 'wdm', '~> 0.1.0' if Gem.win_platform?
gem 'webrick'
gem 'bigdecimal'
gem 'csv'
gem 'logger'
gem 'base64'
